module.exports={ 
    theGoods =[
{title: "Which built-in loop method calls a function for each element in the array?",
choices: ["while()", "for()", "forEach()", "none of the above"],
answer: "forEach loop" == true,
},
{title: "Which built-in method returns the index within the calling String object of the first occurrence of the specified value?",
choices: ["getIndex()","location()","indexOf()","None of the above"],
answer: "indexof()" == true,
},
{title: "Which built-in method returns the length of the string?",
choices: ["length()","size()","index()","none of the above"],
answer: "length" == true,
},
{title: "Which built-in method reverses the order of the elements of an array?",
choices: ["changeOrder(order)","reverse()","sort(order)","None of the above"],
answer: "reverse()",
},
{title: "Which built-in method returns the characters in a string beginning at the specified location?",
choices: ["substr()","getSubstring()","slice()", "None of the above"],
answer: "substr()",
},
{title: "Which built-in method returns the calling string value converted to lower case?",
choices: ["toLowerCase", "toLower", "changeCase(case)", "none of the above"],
answer: "toLowerCase",
},
{title: "Which of the following function of Number object formats a number with a specific number of digits to the right of the decimal?",
choices: ["toExponential()", "toFixed()", "toPrecision()", "toLocaleString()"],
answer:"toFixed()",
},
{title: "Which of the following function of Number object defines how many total digits to display of a number?",
choices: ["toExponential()", "toFixed()","toLocaleString()","toPrecision()"],
answer: "toPrecision()",
},
{title: "Which of the following function of String object returns the character at the specified index?",
choices: [ "charAt()", "charCodeAt()", "concat()", "indexOf()"],
answer: "charAt()",
},
{title:"Which of the following function of String object combines the text of two strings and returns a new string?",
choices: ["add()", "merge()", "concat()", "append()"],
answer: "concat()",
}]
}

var titleArray = [
    "Which built-in method calls a function for each element in the array?",
    "Which built-in method returns the index within the calling String object of the first occurrence of the specified value?",
    "Which built-in method returns the length of the string?",
    "Which built-in method reverses the order of the elements of an array?",
    "Which built-in method returns the characters in a string beginning at the specified location?",
    "Which built-in method returns the calling string value converted to lower case?",
    "Which of the following function of Number object formats a number with a specific number of digits to the right of the decimal?",
    "Which of the following function of Number object defines how many total digits to display of a number?",
    "Which of the following function of String object returns the character at the specified index?",
    "Which of the following function of String object combines the text of two strings and returns a new string?",
];
var aChoiceArray = ["while()", "getIndex()", "length()", "changeOrder(order)",
 "substr()", "toLowerCase", "toExponential()",
"toExponential()", "charAt()", "add()",]



